###
GET http://localhost:8080/accounts

###
GET http://localhost:8080/account/41108fd3-f50d-4bfd-b168-5e9cbbda9a77

###
POST http://localhost:8080/account/create
Content-Type: application/json

{}

###
PUT http://localhost:8080/account/replenish
Content-Type: application/json

{"id": "41108fd3-f50d-4bfd-b168-5e9cbbda9a77", "amount": 250}

###
PUT http://localhost:8080/account/withdraw
Content-Type: application/json

{"id": "d7875c47-51bd-461d-9b49-73ec1e81ca13", "amount": 300}

###
PUT http://localhost:8080/account/transfer
Content-Type: application/json

{"idFrom": "d7875c47-51bd-461d-9b49-73ec1e81ca13", "idTo": "41108fd3-f50d-4bfd-b168-5e9cbbda9a77", "amount": 175}

###
DELETE http://localhost:8080/account/8b1d77f0-cfd3-4039-b853-ad766d3e8eee