###
GET http://localhost:8080/accounts

###
GET http://localhost:8080/account/c8618d0e-99e5-4cd4-bf9d-0d7764be8150

###
POST http://localhost:8080/account/create
Content-Type: application/json

{}

###
PUT http://localhost:8080/account/replenish
Content-Type: application/json

{"id": "c8618d0e-99e5-4cd4-bf9d-0d7764be8150", "amount": 500}

###
PUT http://localhost:8080/account/withdraw
Content-Type: application/json

{"id": "c8618d0e-99e5-4cd4-bf9d-0d7764be8150", "amount": 300}

###
PUT http://localhost:8080/account/transfer
Content-Type: application/json

{"idFrom": "c8618d0e-99e5-4cd4-bf9d-0d7764be8150", "idTo": "0a126671-8a68-4391-bd07-16a12f7bcb2e", "amount": 150}

###
DELETE http://localhost:8080/account/0a126671-8a68-4391-bd07-16a12f7bcb2e