version: '3.1'

services:
  db:
    image: postgres:9.6
    container_name: postgres-misis
    environment:
      POSTGRES_PASSWORD: 1111
    ports:
      - 5434:5432

  system-fast-payments:
    image: misis-system-fast-payments
    container_name: misis-system-fast-payments
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    environment:
      PGHOST: db
      PGPORT: 5432
    ports:
      - 8080:8080